### ISSUE TITLE
Discover: WherePrimaryReleaseDateIsAfter and WherePrimaryReleaseDateIsBefore remove each other

### ISSUE THREAD

**Issue by hims889** [LordMike/TMDbLib#338] opened 2020-07-19 04:02 UTC
Hi,

I am searching movies using Discover API in between two specific dates but it is showing all movies even after passing date parameter. I am using following code. can you please check what i am doing wrong.

await TmdbAccessor.Client.DiscoverMoviesAsync().WherePrimaryReleaseDateIsAfter(DateTime.Now).WherePrimaryReleaseDateIsBefore(DateTime.Now.AddDays(7)).OrderBy(TMDbLib.Objects.Discover.DiscoverMovieSortBy.PrimaryReleaseDate).Query(input.PageNumber);

Thanks

**Comment by LordMike** [comment] 2020-07-20 07:59
It _looks_ correct.. you're certain the movies you get have a primary release date that is outside your 7 day period?

**Comment by LordMike** [comment] 2020-07-20 08:00
Oooh.. I see. In the code, we remove the _other_ parameter when you set one of them..

I think I hadn't considered using both parameters at once.

**Comment by LordMike** [comment] 2020-08-16 18:53
The issue is resolved in PR #341 - I didn't take your #340 as it also changes how the method works. I'll go for an approach where you can't undo the changes to the discover objects, else they'd have to be designed differently entirely.

**Comment by LordMike** [comment] 2020-08-16 18:54
Fixed in 1fea813399a0aa7d409f18b2fb65177eb904ecdd

**Closed by LordMike** 2020-08-16 18:53 UTC
Labels: bug
